---
version: '3.4'

services:

    aiidalab:
        image: ${REGISTRY:-}aiidalab/full-stack:2022.1001
        environment:
            TZ: Europe/Zurich
            DOCKER_STACKS_JUPYTER_CMD: notebook
            SETUP_DEFAULT_AIIDA_PROFILE: 'true'
            AIIDALAB_DEFAULT_APPS: ''
        volumes:
            - aiidalab-home-folder:/home/jovyan
        ports:
            - "0.0.0.0:${AIIDALAB_PORT:-}:8888"

volumes:
    aiidalab-home-folder:
