---
version: '3.4'

services:

    database:
        image: postgres:12.3
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - aiida-postgres-db:/var/lib/postgresql/data
        healthcheck:
            interval: 5s
            timeout: 5s
            retries: 10

    messaging:
        image: rabbitmq:3.8.3-management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - aiida-rmq-data:/var/lib/rabbitmq/

    aiida:
        image: 88ed76fefd33
        environment:
            RMQHOST: messaging
            TZ: Europe/Zurich
            SETUP_DEFAULT_AIIDA_PROFILE: 'true'
        volumes:
            - aiida-home-folder:/home/aiida
        depends_on:
            database:
                condition: service_started
            messaging:
                condition: service_started
        command: tail -f /dev/null

volumes:
    aiida-postgres-db:
    aiida-rmq-data:
    aiida-home-folder:
