---
name: Build environment
description: Create build environment

inputs:
    architecture:
        description: architecture to be run on
        required: true
        type: string

runs:
    using: composite
    steps:
        - name: Set Up Python 🐍
          uses: actions/setup-python@v4.0.0
          with:
              python-version: 3.11

        - name: Install dependencies 📦
          run: pip install -r requirements-dev.txt
          shell: bash -e {0}
