---
name: Python environment
description: Create Python environment and install dependencies for running tests

inputs:
    runner:
        description: Github Actions runner
        required: true
        type: string

runs:
    using: composite
    steps:
    # actions/setup-python doesn't support Linux arm64 runners
    # See: https://github.com/actions/setup-python/issues/108
    # python3 is manually preinstalled in the arm64 VM self-hosted runner
        - name: Set Up Python 🐍
          if: ${{ inputs.runner != 'ARM64' }}
          uses: actions/setup-python@v5
          with:
              python-version: '3.11'
              cache: pip
              cache-dependency-path: |
                  **/requirements*.txt

        - name: Install dependencies 📦
          run: pip install -r requirements-dev.txt
          shell: bash
