---
name: Build images upload them to ghcr.io

env:
    OWNER: ${{ github.repository_owner }}
    REGISTRY: ghcr.io

on:
    workflow_call:
        inputs:
            image:
                description: Image name
                required: false
                type: string
            architecture:
                description: Image architecture, e.g. amd64, arm64
                required: true
                type: string
            runsOn:
                description: GitHub Actions Runner image
                required: true
                type: string

jobs:
    build-upload:
        runs-on: ${{ inputs.runsOn }}
        timeout-minutes: 20

        steps:

            - name: Checkout Repo ⚡️
              uses: actions/checkout@v4

              #- name: Set up QEMU
              #uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ inputs.image }}
                  tags: |
                      type=sha
                      type=ref,event=pr

            - name: Build image
              id: build
              uses: docker/bake-action@v4
              with:
                  # tags: ${{ steps.meta.outputs.tags }}
                  # platforms: ${{ inputs.architecture }}
                  push: false
                  # Using provenance to disable default attestation so it will build only desired images:
                  # https://github.com/orgs/community/discussions/45969
                  provenance: false
                  files: |
                      docker-bake.hcl
                      build.json
