---
name: Download Docker image and its tags from GitHub artifacts, apply them and push the image to DockerHub

env:
    # OWNER: ${{ github.repository_owner }}
    OWNER: jusong

on:
    workflow_call:
        inputs:
            image:
                description: Image name
                required: true
                type: string
            architecture:
                description: Image architecture
                required: true
                type: string
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true

jobs:
    tag-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo ⚡️
              uses: actions/checkout@v3
            - name: Create dev environment 📦
              uses: ./.github/actions/create-dev-env
              with:
                  architecture: x86_64
            - name: Load image to Docker 📥
              uses: ./.github/actions/load-image
              with:
                  image: ${{ inputs.image }}
                  architecture: ${{ inputs.architecture }}

            - name: Login to Docker Hub 🔐
        # if: github.repository == 'aiidalab/aiidalab-docker-stack' && (github.ref == 'refs/heads/main' || github.event_name == 'schedule')
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: delete newly-build tag

            - name: Push Images to Docker Hub 📤
        # if: github.repository == 'aiidalab/aiidalab-docker-stack' && (github.ref == 'refs/heads/main' || github.event_name == 'schedule')
              #run: docker push --all-tags ${{ env.OWNER }}/${{ inputs.image }}
              run: docker push --all-tags ${{ env.OWNER }}/${{ inputs.image }}
              shell: bash
