#!/bin/bash
set -e

# For each target that is part of the "default" group, replace the term
# "__template__" in the provided template bake-file, and then merge all
# resulting bake-files into one.
#
# That means if the default group contains a target named "base", the script
# will replace all occurrences of the term "__template__" with "base" and then
# merge the result with those for all other targets part of the "default" group.
#
# The motivation is to be able to use a bake-file generated by the
# docker/meta-action (which can currently only handle a single bake-target) for
# all targets currently specified in the main bake-file ("docker-bake.hcl").

input=$(cat; echo x)
input=${input%x}   # Strip the trailing x

# Determine the targets.
TARGETS=$(docker buildx bake --print | jq -cr '.group.default.targets' | jq -r '.[]')

# Generate the meta JSON strings
meta=""
for target in $TARGETS; do
  meta="${meta} ${input//__template__/${target}}"
done

# Combine into merged bake file.
echo $meta | jq -s 'reduce .[] as $x ({}; . * $x)'
