#!/bin/bash
set -euo pipefail

# For each target that is part of the "default" group, replace the term
# "__template__" in the provided template bake-file, and then merge all
# resulting bake-files into one.
#
# That means if the default group contains a target named "base", the script
# will replace all occurrences of the term "__template__" with "base" and then
# merge the result with those for all other targets part of the "default" group.
#
# The motivation is to be able to use a bake-file generated by the
# docker/meta-action (which can currently only handle a single bake-target) for
# all targets currently specified in the main bake-file ("docker-bake.hcl").
#
if [[ -z ${1-} ]];then
  echo "ERROR: Provide path to bake-file template as first parameter"
  exit 1
fi

input_file=$1
if [[ ! -f ${input_file} ]];then
  echo "ERROR: File $input_file does not exist!"
  exit 1
fi

# Flatten the json file into a single line
input=$(cat $input_file | jq -c)

# Determine the targets.
TARGETS=$(docker buildx bake --print | jq -cr '.group.default.targets' | jq -r '.[]')

# Generate the meta JSON strings
meta=""
for target in $TARGETS; do
  meta="${meta} ${input//__template__/${target}}"
done

# Combine into merged bake file.
echo $meta | jq -s 'reduce .[] as $x ({}; . * $x)'
