---
# Build and push images to DockerHub

name: release-images

on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*

jobs:

    build-and-push-docker-images:

        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build images with buildx bake
              uses: docker/bake-action@v2.2.0
              with:
                  push: true
